# These categories will be applied to all DAGs in the repo.
categories:
  - ETL/ELT
  - Big Data & Analytics
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/census-sync-dw-to-marketing.py